### ISSUE TITLE
Upload file with name longer than 40 characters

### ISSUE THREAD

**Issue by petrmaly12** [Topher84/NetSuite-Tools-For-WebStorm#13]
I've been getting this error message: "The field caption contained more than the maximum number (40) of characters allowed." I just want to ask, is this a restriction of WebStorm plugin or NetSuite webservices? Because it is allowed to add file with name longer than 40 characters to the file cabinet in NetSuite via UI.
Thanks.

**Comment by Topher84** [comment]
This is a NetSuite limitation and not something controlled in the plugin That error message that is displayed is what NetSuite is returning. I (and some team members) have run into this issue as well when uploading new files (I believe when you upload new file, it just copies the name to the caption field). I personally usually try to rename the file to something that meets the character limit. Unfortunately, there is nothing I can do via the plugin other than chopping off the character limit which I would rather not mess with people's data.

**Comment by petrmaly12** [comment]
I see, thanks for the information.
