### ISSUE TITLE
Upload ide freezing

### ISSUE THREAD

**Issue by Ruplahlava** [Topher84/NetSuite-Tools-For-WebStorm#14]
Hi, thank you for this plugin, much better than NS provided eclipse one...
However there is an issue - while uploading files, ide freezes for a while, and when uploading multiple ones it can freeze for minutes.
Some background task in webstorm for that would be awesome! :)

**Comment by sclearion** [comment]
same here. the more files, the longer the freeze

**Comment by Topher84** [comment]
No problem @Ruplahlava 

The freeze is the IDE uploading the file as it isn't asynchronous. I can look into making it asynchronous. My original thought was that I want to get feedback before I move on from uploading so that I don't miss out on something that was in error. I'll add this as an enhancement to investigate.

**Comment by Topher84** [comment]
Just as an update, I have some background threading implemented for uploading files. I may also add it to the compare action as well. I will test the upload out tomorrow and possibly add the compare action as well and if all is good, will make a release.

**Comment by Ruplahlava** [comment]
Thank you for such a quick response, that sounds awesome!

**Comment by Topher84** [comment]
Sorry for the slowness on this, had some life things pop up. Release 1.0.12 should have uploading and comparing as background tasks now so no more IDE freezing. I also made some code cleanup as I was doing a few things that weren't needed. Please give this release a go. If you have any issues, please open a new issue and I will see what I can do. Thanks for using my plugin!

**Comment by Ruplahlava** [comment]
Thanks! Will look at it on monday...
