### ISSUE TITLE
Cannot "remove" settings?

### ISSUE THREAD

**Issue by sclearion** [Topher84/NetSuite-Tools-For-WebStorm#15]
Does this plugin cache credentials outside of the project folder? Reason being:

- I install+setup the plugin for new project
- I uninstall the plugin + remove .idea folder + hidden files
- I reinstall plugin
- Plugin remembers last username/password !!!

I need to remove this caching being that it is extraneous to the project folder (git). where can I remove them

**Comment by Topher84** [comment]
I see that you've closed this but for a better understanding, the passwords are saved in the Keychain Access on Mac or Windows Password Manager. If you're curious how project settings work, the file that contains this logic is:

https://github.com/Topher84/NetSuite-Tools-For-WebStorm/blob/master/src/projectsettings/ProjectSettingsController.java
Submenus when you right click on the project are only available if the hasAllProjectSettings method returns true.
