### ISSUE TITLE
Unable to set root folder to SuiteScripts via UI

### ISSUE THREAD

**Issue by MystK** [Topher84/NetSuite-Tools-For-WebStorm#16]
Why is there code to not allow setting the root folder to SuiteScripts folder even though it can manually be done via the folder ID?

**Comment by Topher84** [comment]
NetSuite's own Eclipse IDE doesn't allow this so I took some direction from that and and didn't allow it from the UI. As you've stated though, you can enter -15 in the box and use SuiteScripts as the root. A good practice is to NOT use suitescripts as the root and make a folder for your project within suitescripts and use that.
