### ISSUE TITLE
NetSuite Webservice Domain for na1

### ISSUE THREAD

**Issue by seanlin816** [Topher84/NetSuite-Tools-For-WebStorm#2]
I have apply for NetSuite Developer Network and I got a brand new set up of HoneyMfg setup.
The domain is system.na1.netsuite.com, is it possible to add a environment like "Developer Network" environment?

Thank you.

**Comment by Topher84** [comment]
system.n1.netsuite.com is a "Production" Account since there is no "sandbox" in the url. A non-production account usually is something like system.sandbox.netsuite.com. If you are trying to pick an environment, you should be able to select "Production" and be fine.
