### ISSUE TITLE
(Question) Can I connect to a customer which has 2 sandboxes?

### ISSUE THREAD

**Issue by RezaSeedin** [Topher84/NetSuite-Tools-For-WebStorm#21]
Hey Mate,

I have been using your tool with like 20 customers and all works perfectly except this one customer who has 2 sandboxes. Customer has webservices switched as well which I thought was the only requirement for your tool to work and have been trying to figure this out for a while. 

Given below you can see a screenshot of what I see.
![image](https://user-images.githubusercontent.com/18523110/28447685-bd14a404-6e15-11e7-8ff3-b6a7604eeef0.png)

when selecting either sandbox I get a invalid login message
![image](https://user-images.githubusercontent.com/18523110/28447748-3005a8be-6e16-11e7-886d-13daa5423c69.png)
Sandbox 2 has the same ID but with "_SB2"

Is there something I can check to see whats going on? I suspect it's something to do with the account rather than the tool?

Any advice would be appreciated.

Keep up the good work

Reza

**Comment by Topher84** [comment]
It 99.99% isn't the tool. If you can't log in, its most likely due to a setup issue on the account itself. I would make sure webservices is turned on.

**Comment by Topher84** [comment]
Going to close this for now. If you are still having issues, reach out to me in the NetSuite Professionals slack channel or feel free to re-open/discuss in this issue.
