### ISSUE TITLE
Keeping upload failed

### ISSUE THREAD

**Issue by lincecumHao** [Topher84/NetSuite-Tools-For-WebStorm#22]
I am pretty sure I have correct parent folder id and all setting were just fine,

but once I upload my file to file cabinet, webstorm shows me:

'You have entered an Invalid Field Value XXX for the following field: url.

I have try reset my project setting, and reinstall the netsuite tool, but the error keeps showing.

And ideal?

**Comment by Topher84** [comment]
Yeah that's a NetSuite error. The plugin just catches errors thrown by NetSuite when data is uploaded. I would check your url data type in your code that's throwing the error and make sure it is valid. For example sometimes I have a syntax error and when I upload, I'll get an error stating the issue.
