### ISSUE TITLE
Account selection menu is empty

### ISSUE THREAD

**Issue by andrewrussell** [Topher84/NetSuite-Tools-For-WebStorm#26]
After I enter my credentials, the next menu shows four columns (account name, account id, role name, role id), but there are no rows.  Is there some permission in NetSuite that I need to set?

**Comment by Topher84** [comment]
Webservices needs to be enabled and most likely suitescripts as well. If you're logging in and getting to the account selection scree, your credentials are correct at least. Is this a new user? Does this user have Full Access or Admin? It needs to be one of these 2 types of accounts.

**Comment by andrewrussell** [comment]
Ok, the account I have to use is neither of those.   Thanks.
