### ISSUE TITLE
[Enhancement] - Use tool as deployment

### ISSUE THREAD

**Issue by Ruplahlava** [Topher84/NetSuite-Tools-For-WebStorm#27]
Hello,
would it be difficult to make this tool to work as deployment  type in (web)storm?

**Comment by Topher84** [comment]
I am not sure what you are asking honestly. Could you please clarify?

**Comment by Ruplahlava** [comment]
If you go to Settings -> Build, execution, deployments -> Deployments there are several types of deployment.
When you try to create one, there is a dropdown with types.
There are several great functions which intellij provides for deploying...

**Comment by Topher84** [comment]
You may be able to setup something if you have one of those settings there, but that is outside the scope of anything I am going to do with this plugin. You can already upload the files/folders so I am not sure what else you would need to do. If you want a deployment tool for doing some things you can setup SDF CLI or make a restlet or something you can connect to and do whatever you want when your specified event occurs but again, that is outside what I am going to do.

**Comment by Ruplahlava** [comment]
Thats why my question was: would it be difficult? :smile: 
I wanted to do some on file change upload for file pattern - webstorm can do it easily with deployments and i dont want to write it again and sdf cli is annoying for asking for password all time.
