### ISSUE TITLE
Unable to select SuiteScripts folder when set up project

### ISSUE THREAD

**Issue by seanlin816** [Topher84/NetSuite-Tools-For-WebStorm#28]
Given using NetSuite Tool For WebStorm v1.1.0, When I tried to set up project and I select SuiteScripts Folder as project root folder, then it prompts an error message of "Cannot set directory to SuiteScripts. Please select another folder".

![screen shot 2017-10-05 at 01 18 15](https://user-images.githubusercontent.com/2238725/31189546-2adf98d6-a8fe-11e7-8f0c-bd480c201c9d.png)

![screen shot 2017-10-05 at 01 10 14](https://user-images.githubusercontent.com/2238725/31189428-d2071130-a8fd-11e7-932f-12febc05fca1.png)

**Comment by Topher84** [comment]
https://github.com/Topher84/NetSuite-Tools-For-WebStorm/issues/16
