### ISSUE TITLE
Duplicate Files Uploaded to Wrong Path

### ISSUE THREAD

**Issue by Godrules500** [Topher84/NetSuite-Tools-For-WebStorm#29]
When I upload files to NetSuite, I go into the file cabinet and see where multiple times several files are uploaded to the root directory instead of the main directory. It seems random, so I'm not sure how to reproduce it. I just know it happens very often.

**Comment by Topher84** [comment]
What does root directory refer to here vs main directory? Do you have multiple directories with the same name? If you set the "root" of your project, anything uploaded is relative to that root (/SuiteScripts/Godrules500 for example so nothing should be uploaded outside of that directory only within). Can you try re-setting up your project and see if you still get this issue? With being random like you say, it is difficult to reproduce it without any further information.
