### ISSUE TITLE
Email address with "+" character

### ISSUE THREAD

**Issue by Kenji-O** [Topher84/NetSuite-Tools-For-WebStorm#3]
It occurs error when assign NetSuite account to WebStorm project.
It seems this happens if email address contains "+".

**Comment by Topher84** [comment]
Thanks for the report. I am going to have to look into this one. I changed my login to include a "+" symbol and I was able to successfully log into NetSuite. However, I was not able to use that same e-mail in a GET request to the NetSuite Roles Rest Service. I am not sure if it is something I need to do or there's an issue with NetSuite. I'll look into this and see if there is a fix.

**Comment by GRUBES** [comment]
I have definitely seen certain special characters in passwords break the SuiteTalk SOAP requests, so I imagine there's a similar problem for emails. Probably need to URL-encode all the values in the `NLAuth` header. We fixed the issue with the password by changing the password on the account; that's much less feasible for email addresses though.

**Comment by Topher84** [comment]
I believe I have found a solution to this issue. I will be releasing a new version shortly. @Kenji-O could you please update to the latest version (probably within the next hour or so) and let me know if that fixes your issue?

**Comment by Topher84** [comment]
I believe I have found

**Comment by Topher84** [comment]
I have just released version 1.0.6 to the Jetbrains Plugin Repository (https://plugins.jetbrains.com/plugin/8305?pr=). Please update to this version and let me know if your issue is solved.

**Comment by Kenji-O** [comment]
@Topher84 fantastic! The issue was resolved.
Now it allows me to use email address with "+" as credential.
Thank you very much. :)

**Comment by Topher84** [comment]
@Kenji-O great! Thanks for reporting the issue and using my plugin! I hope it works well for you.
