### ISSUE TITLE
Error Searching/Creating Folder

### ISSUE THREAD

**Issue by Godrules500** [Topher84/NetSuite-Tools-For-WebStorm#30]
When I try to upload the files to netsuite I am getting an "Error Searching/Creating Folder". I also tried to change the project settings and got an error in regards to sub folders.

Here is the response.

`<?xml version="1.0"?>

-<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

-<soapenv:Header>

-<platformMsgs:documentInfo xmlns:platformMsgs="urn:messages_2017_1.platform.webservices.netsuite.com">

<platformMsgs:nsId>WEBSERVICES_4268509_1115201710711210231283504309_fedbc065d98</platformMsgs:nsId>

</platformMsgs:documentInfo>

</soapenv:Header>

-<soapenv:Body>

-<addResponse xmlns="urn:messages_2017_1.platform.webservices.netsuite.com">

-<writeResponse>

-<platformCore:status xmlns:platformCore="urn:core_2017_1.platform.webservices.netsuite.com" isSuccess="false">

-<platformCore:statusDetail type="ERROR">

<platformCore:code>USER_ERROR</platformCore:code>

<platformCore:message>A folder with the same name already exists in the selected folder.</platformCore:message>

</platformCore:statusDetail>

</platformCore:status>

</writeResponse>

</addResponse>

</soapenv:Body>

</soapenv:Envelope>`

**Comment by Godrules500** [comment]
also:

<?xml version="1.0"?>

-<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">


-<soapenv:Header>


-<platformMsgs:documentInfo xmlns:platformMsgs="urn:messages_2017_1.platform.webservices.netsuite.com">

<platformMsgs:nsId>i removed this</platformMsgs:nsId>

</platformMsgs:documentInfo>

</soapenv:Header>


-<soapenv:Body>


-<searchResponse xmlns="urn:messages_2017_1.platform.webservices.netsuite.com">


-<platformCore:searchResult xmlns:platformCore="urn:core_2017_1.platform.webservices.netsuite.com">


-<platformCore:status isSuccess="false">


-<platformCore:statusDetail type="ERROR">

<platformCore:code>INVALID_KEY_OR_REF</platformCore:code>

<platformCore:message>The specified key is invalid.</platformCore:message>

</platformCore:statusDetail>

</platformCore:status>

</platformCore:searchResult>

</searchResponse>

</soapenv:Body>

</soapenv:Envelope>

**Comment by Topher84** [comment]
We discussed this issue via Slack and the issue went away on its own. Not sure what the issue was on the NetSuite side. Closing this for now.
