### ISSUE TITLE
Intellij Dont know if plugin its working

### ISSUE THREAD

**Issue by skAvatar** [Topher84/NetSuite-Tools-For-WebStorm#32]
#Hello,
    Im installing NetSuite-Tools-For-WebStorm 1.1.0 from https://plugins.jetbrains.com/plugin/8305-netsuite-tools-for-webstorm but the IDE dont show a new menu like 
eclipse when install this same plugin. Inclusive the option Netsuite Tools it does not show anywhere. But through keymap i found how to configurate Netsuite Account and logging was succesfull. For last when i create a new project i dont see the option new suite script project.

![plugin_1](https://user-images.githubusercontent.com/30122269/34586200-594de380-f179-11e7-969f-e4337ff104ad.PNG)
![plugin_2](https://user-images.githubusercontent.com/30122269/34586201-5968068e-f179-11e7-854b-0b90c3dc61bb.PNG)
![plugin_3](https://user-images.githubusercontent.com/30122269/34586202-5980494c-f179-11e7-9516-0f683123ff1b.PNG)

regards... xD plz help   @Topher84

**Comment by Topher84** [comment]
You have to start a new project and then you right click on the project folder in the side bar and its towards the bottom for "NetSuite Tools For Webstorm" and has the option to set up a project or view the records browser.

**Comment by skAvatar** [comment]
Hello Ty ..... sorry for making you wasting time

But its all fine, i can upload my files THANKS to you!!!!!!
