### ISSUE TITLE
Plugin not showing

### ISSUE THREAD

**Issue by jk121960** [Topher84/NetSuite-Tools-For-WebStorm#33]
Hi, I just upgraded my Webstorm from 2017.2 - build 172.4343.25 to 2017.3 - build 173.4127.31 and the plugin disappeared, I uninstalled and reinstalled and it shows installed but does not appear in any of the menus. I had been using it in the project>file popup location so I checked the menu editor and it is still there but does not show when you right click on a file in the project tab. I temporarily hooked the commands up to shortcuts and they work but having in the file context menu was very convenient. I have been using it for sometime in that position and it was fine. If I load up the old version of Webstorm it is still working there, just on the newest version is this a problem. thanks again for the plugin it is awesome

**Comment by Topher84** [comment]
I am using the same build and everything appears to be functioning normally (on MacBook). The option has only ever been available via right clicking on the project or a file within a project and going to NetSuite Tools in the menu. I also just tried on a newly formatted MacBook and it works just fine. If you're hooking it up via shortcuts and its still working, it may be that you've accidentally removed it as a menu option somewhere. If you go to settings and then "Menus and Toolbars" and then "Project View Popup Menu" you should see "NetSuite Tools" in there. You may have to adjust a setting in there. This isn't something that I am aware of ever happening and appears to be more of a Webstorm issue than the plugin issue. If you can take a look we may be able to resolve this either way.

**Comment by jk121960** [comment]
Thanks for the quick response, I have looked in that area and everything looks fine. I have included a screenshot of the "menu editor"  showing the entry as it appears in the settings 
![image](https://user-images.githubusercontent.com/1699012/34945779-11de8532-f9ca-11e7-899c-44ac06bb0045.png)

**Comment by jk121960** [comment]
I submitted an issue to Jetbrains I will let you know the result, thanks

**Comment by Topher84** [comment]
This is over a month old and has not had any movement. Going to consider this resolved/no longer an issue. If something occurs, feel free to start a new issue.
