### ISSUE TITLE
Error with plugin: java.lang.NoClassDefFoundError: org/codehaus/jettison/json/JSONArray

### ISSUE THREAD

**Issue by ehcanadianCA** [Topher84/NetSuite-Tools-For-WebStorm#34]
Hello,

When I attempt to connect to NS I get the following error:

```
org/codehaus/jettison/json/JSONArray
java.lang.NoClassDefFoundError: org/codehaus/jettison/json/JSONArray
	at netsuite.NSRolesRestServiceController.getNSAccountsList(NSRolesRestServiceController.java:76)
```

I assume this is because I am missing a library or something but I am new to WebStorm. Any ideas on how I can fix this?

Thank you!

**Comment by Topher84** [comment]
All you should need to do is download the plugin and it should work just fine. You are the first person that has brought up an issue like this. Did you try reinstalling the plugin by chance?

**Comment by t4eron** [comment]
Hello, 

Actually I am subscribed to this issue and I have encountered the exact same error this week as well. I have reinstalled the plugin a couple times. I downloaded the latest version of WebStorm and your plugin directly from JetBrains' page. 

Please advise, I have the exact same error:

`org/codehaus/jettison/json/JSONArray
java.lang.NoClassDefFoundError: org/codehaus/jettison/json/JSONArray
	at netsuite.NSRolesRestServiceController.getNSAccountsList(NSRolesRestServiceController.java:76)`

Thank you!

**Comment by ehcanadianCA** [comment]
I tried reinstalling the plugin. I downloaded version 1.1.0 from the JetBrains plugin page. That didn't help though. I'm out of ideas.

**Comment by Topher84** [comment]
It seems like you both have downloaded off the plugin site. Have you tried downloading via the plugin browser in the IDE? I don't see why it would make a difference but I just tried this on a new install and everything is working just fine.

**Comment by ehcanadianCA** [comment]
Uninstalling the plugin and then installing it via the plugin browser in the IDE solved this. Thank you!!

**Comment by t4eron** [comment]
Same here. Thank you very much!

**Comment by Topher84** [comment]
Going to close this since it appears to be resolved.
