### ISSUE TITLE
File name over 40 character error.

### ISSUE THREAD

**Issue by lincecumHao** [Topher84/NetSuite-Tools-For-WebStorm#35]
Hello, 
when I try upload a file with file name length over 40 chartacter shows that it's not allowed,
but Eclipse won't have this problem, so it's the limit from Netsuite or this plugin?
Any chance or clue that I can fix it?

**Comment by Ruplahlava** [comment]
Hey @lincecumHao ,
40 characters is "best practise" in NS. Eclipse might allow it, but then you might have issue with SDF, etc...
I would try to limit your file names to 40 chars.

**Comment by lincecumHao** [comment]
Hi @Ruplahlava ,
Thanks for the quick reply, I'll limit my file names in the future 😝
