### ISSUE TITLE
Upload Threads

### ISSUE THREAD

**Issue by jk121960** [Topher84/NetSuite-Tools-For-WebStorm#36]
Hi and thanks, great plugin, a godsend. I updated recently and it seems as though the file uploads are single thread now. Before I could select a group and you could see the overlapping files as they uploaded. Now it seems to wait till one file is finished before uploading the next. I have libraries of files when I start with a client that is taking forever now to upload, changing back would be great. 

thanks

**Comment by Topher84** [comment]
There weren't any updates to any logic around this. Everything is still as it was and I can't replicate this as all selected files are uploading fine. This could have been a data issue that day with NetSuite. If you're still experiencing this feel free to open another issue, but I can't promise I will get to it quickly.

**Comment by jk121960** [comment]
Appreciate it thanks

Gerald Klein DBA

jk121960@gmail.com

jk@zognet.com

708-599-0352


Arch, Gentoo I3, Ranger & Vim the coding triple threat.

Linux registered user #548580

Brought to you by the Amish Mafia
