### ISSUE TITLE
No access after 2FA

### ISSUE THREAD

**Issue by nikolagavric** [Topher84/NetSuite-Tools-For-WebStorm#43]
Hi!

I can't upload files after 2FA was introduced to the admin roles. I've tried the suggestion of creating a SDF Dev role, I've done so, created a new user that I gave the role and tried logging into that user in my project instead of my admin user, but the Role doesn't show up in the list when I get to choose roles. When I add the admin role to my new user it shows in the list, but not my SDF role. Have I missed something in the role setup? I followed every step and added all the permissions mentioned in the NetSuite Help. I think I've tried everything I can think of so help would be appreciated! :)

![ns](https://user-images.githubusercontent.com/3907682/47089412-17cf1080-d221-11e8-85a6-bd9115b0a80a.jpg)

Btw awesome plugin otherwise!

**Comment by Topher84** [comment]
I'm not sure about an SDF role, but all you need for this plugin are the following 3 permissions:

1) Lists -> Documents and Files -> Full
2) Setup -> Webservices -> Full 
3) Setup -> Upload HTML/Javascript -> Full

I've also been making the roles "webservices only" since it doesn't need to be something that you can log in with. Trying to keep the permissions/actions at a minimum but its not required.

Then assign that role to the same user you are logging in with and it should show up in the list.

**Comment by nikolagavric** [comment]
> I'm not sure about an SDF role, but all you need for this plugin are the following 3 permissions:
> 
> 1. Lists -> Documents and Files -> Full
> 2. Setup -> Webservices -> Full
> 3. Setup -> Upload HTML/Javascript -> Full
> 
> I've also been making the roles "webservices only" since it doesn't need to be something that you can log in with. Trying to keep the permissions/actions at a minimum but its not required.
> 
> Then assign that role to the same user you are logging in with and it should show up in the list.

Thanks for the reply! I tried to follow the above (added 3. to my role as it was missing) but it didn't help. Also tried creating a new role with only the above three permissions and still doesn't work. Permission 3 has a slightly different name here (Allow JS / HTML Uploads) but should be exactly the same thing.. So I'm a little lost here, any other ideas?

**Comment by nikolagavric** [comment]
> I'm not sure about an SDF role, but all you need for this plugin are the following 3 permissions:
> 
> 1. Lists -> Documents and Files -> Full
> 2. Setup -> Webservices -> Full
> 3. Setup -> Upload HTML/Javascript -> Full
> 
> I've also been making the roles "webservices only" since it doesn't need to be something that you can log in with. Trying to keep the permissions/actions at a minimum but its not required.
> 
> Then assign that role to the same user you are logging in with and it should show up in the list.

Tried all of the above both on a current role and created a new role with only the three permissions above but it didn't work, still doesn't show up. Any other ideas?

**Comment by rs77** [comment]
I ran into the same 2FA problem today with my Admin account. I created a new role, added the 3 permissions, ticked "Web services only", added it to my user account and then changed my settings to use that role in my project and worked first time.

Thank you!

**Comment by Topher84** [comment]
Issue is definitely resolved using the permissions listed. If you mess up the role and don't apply the correct permissions the first time, it seems like NetSuite takes a bit to refresh the roles for some reason so I usually just delete the role and start over. I am closing this issue for now.

**Comment by Godrules500** [comment]
I am having the issue today. I have created the above role, giving the allow html/js uploads permission, but I am still getting the "You need permission `Allow JS/html Upload'"

Any thoughts on why I am receiving this issue, even though I have the permission?

**Comment by Topher84** [comment]
@Godrules500 If you recently updated an EXISTING role, then in my experience, it takes a while for NetSuite to realize this. I typically make a "developer" role and assign it. If i mess it up, I delete and start over or NetSuite is going to take forever.
