### ISSUE TITLE
Can't login with 2020.2 Netsuite

### ISSUE THREAD

**Issue by batosti** [Topher84/NetSuite-Tools-For-WebStorm#48]
When I try to login with 2020.2 Netsuite account i got this error:
![image](https://user-images.githubusercontent.com/5798162/96454847-cf250600-11f2-11eb-89c6-7fef693a2e41.png)

Have a way to login with this account? We need to update the plugin to work with 2FA to make this work? If I can help with this, let me know.

**Comment by DiagJuanma** [comment]
I am having the same issue.

**Comment by batosti** [comment]
I solved using another webstorm plugin to netsuite. Provided by netsuite. But the working directories are quite different. The instructions are in netsuite's documentation
