### ISSUE TITLE
Plugin shows that files are uploaded even if they fail NetSuite validation

### ISSUE THREAD

**Issue by mdrobbins** [Topher84/NetSuite-Tools-For-WebStorm#5]
SuiteScript 2.0 files have some sort of validation performed on them by NetSuite when they are uploaded to the file cabinet.  If they fail this validation, NetSuite returns and error and prevents the upload.  NTFW will still display the "Files Uploaded" informational alert even if the uploaded file fails validation.

There are two scenarios in which I have seen this behavior;

- Trying to upload a v2.0 script file over the top of a v1.0 script file results in "Failed to validate script file:  This file is used by a SuiteScript 1.0 script; you cannot change the API version of the file."
- Trying to upload a v2.0 script file that doesn't have at least one correct entry point defined for the specified script type results in "SuiteScript 2.0 entry point scripts must implement one script type function".

I've attached the SOAP responses that provide examples of each.  Let me know if I can help in any way.

[Entry Points.txt](https://github.com/Topher84/NetSuite-Tools-For-WebStorm/files/470512/Entry.Points.txt)

[Failed to validate script file.txt](https://github.com/Topher84/NetSuite-Tools-For-WebStorm/files/470513/Failed.to.validate.script.file.txt)

**Comment by Topher84** [comment]
Thanks for the info. I haven't really tested this much with any 2.0 stuff yet. I see in your examples that we do get an failure for isSuccess and a message with the details. I can add something like a red prompt that will say it failed to upload and popup a message with the details I believe. Is that something like you are expecting? I definitely do not check for isSuccess now which I should be doing.

**Comment by mdrobbins** [comment]
That's exactly what I was thinking.  I'd certainly appreciate it!

**Comment by Topher84** [comment]
I just pushed version 1.0.8 that should fix your issue. Thanks.

**Comment by mdrobbins** [comment]
Just tested it with 1.0.8.  Works like a champ!

Thanks for such a quick turn-around...and thanks for putting together this plugin.  I use it all day every day.

**Comment by Topher84** [comment]
Awesome!

No problem! I used it all day too. Thanks for the kind words.
