### ISSUE TITLE
PluginException on launch

### ISSUE THREAD

**Issue by heathf** [Topher84/NetSuite-Tools-For-WebStorm#7]
I apologize, as maybe I'm doing something incorrectly, but I installed the plugin via Settings>Plugins, and when I launch WebStorm, I get an error message.  The details show: "PluginException: cannot create class "actions.SetupProjectAction" [Plugin: netsuite.tools.plugin]"

If I right click on a project file, there is a 'NetSuite Tools' option, but it's disabled, and pointing to it doesn't expand a fly out menu.  I'm on WebStorm 10.0 on macOS Sierra.  I've tried uninstalling/reinstalling as well as relaunching WS, but keep getting the same results.  I also updated Java, and am now on Java 8 Update 101.  

Thanks for the help.  I'm new to Netsuite, but love WebStorm, so I'm hopeful I can get this working.

**Comment by Topher84** [comment]
Welcome to NetSuite dev and good choice and picking WebStorm as it is a great IDE.

Installing the plugin from the plugin section in settings is correct. My plugin is for build 141 and up which according to the JetBrains Doc (http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html) WebStorm 10 is included.

Another user had what appears to be this exact same issue on the reddit thread and upgrading his pyCharm resolved the issue. 

Thread:
https://www.reddit.com/r/Netsuite/comments/4frfl3/netsuite_tools_for_webstorm_ide/d2dm47z

Is it possible for you to get the latest WebStorm and give it a go?

**Comment by heathf** [comment]
Ya that seems to have done the trick.  My apologies.  I should have thought to do that myself.  

I appreciate the help.  All seems to be working perfectly now.  (I’m psyched about this plugin by the way.  It will make the task at hand much easier and more enjoyable)

Thanks again

**Comment by Topher84** [comment]
Awesome! Glad that worked for you although I am still curious why WebStorm 10 doesn't work when it IS specified as such. 2016.2 is a pretty good release though. Thanks you for using the plugin. It's good to see some other people getting some use out of it. I am going to close this issue since it is resolved.
