### ISSUE TITLE
Save files before upload

### ISSUE THREAD

**Issue by TomasJancik** [Topher84/NetSuite-Tools-For-WebStorm#8]
I've set a keyboard shortcut for the "Upload selected files" action
This way I open the required file, do some modifications and can quickly upload it with the shortcut. But the most recent changes are not upload

I guess it's because the file was not saved ( https://www.jetbrains.com/help/idea/2016.2/saving-and-reverting-changes.html ) 

Could the plugin force save the file(s) before uploading them?

**Comment by Topher84** [comment]
That is the same thing I do. I bind my upload to CMD+U (I use a Mac). I also have a habit of hitting CMD+S (save shortcut) and then CMD+U (upload).

I can add functionality that will save all of the open files before uploading.

**Comment by Topher84** [comment]
I am uploading version 1.0.9 to the repository right now with this enhancement. Thanks for the suggestion and for using the plugin.

**Comment by TomasJancik** [comment]
thanks for the enhancement
